import Image from "next/image";
import rsbbMark from "@/assets/brand/rsbb-mark.png";
import rsbbLogo from "@/assets/brand/rsbb-logo.png";

// Brand assets come from the hospital's logo (generated by .tools/make-brand.py):
// the RSBB mark alone for compact spots, the full logo (with "Rumah Sakit
// Balikpapan Baru") for the login page. Both have transparent backgrounds,
// so they work in light and dark mode.

/** The RSBB mark. Set its height with className; `height` is the largest it's shown at (for srcset). */
export function LogoMark({ className = "h-8", height = 32 }: { className?: string; height?: number }) {
  return (
    <Image
      src={rsbbMark}
      alt="RSBB"
      height={height}
      width={Math.round((height * rsbbMark.width) / rsbbMark.height)}
      priority
      // Height comes from className; keep the width proportional.
      style={{ width: "auto" }}
      className={`shrink-0 ${className}`}
    />
  );
}

/** The full hospital logo. Set its width with className. */
export function FullLogo({ className = "w-56", width = 224 }: { className?: string; width?: number }) {
  return (
    <Image
      src={rsbbLogo}
      alt="Rumah Sakit Balikpapan Baru"
      width={width}
      height={Math.round((width * rsbbLogo.height) / rsbbLogo.width)}
      priority
      style={{ height: "auto" }}
      className={className}
    />
  );
}

export function Logo() {
  return (
    <span className="flex items-center gap-2.5 font-semibold tracking-tight">
      <LogoMark />
      <span aria-hidden="true" className="h-5 w-px bg-border" />
      Stock RSBB
    </span>
  );
}
